// AUTO-GENERATED by scripts/generate-release-meta.mjs
// Do not edit manually.

export const releaseDates: Record<string, string> = {
  "2.1.2": "2026-02-13",
  "2.1.1": "2026-02-12",
  "2.1.0": "2026-02-12",
  "2.0.2": "2026-02-11",
  "2.0.1": "2026-02-11",
  "2.0.0": "2026-02-11"
};

export const latestVersion: string = "2.1.2";
